question_data = [
    {"question": "A slug's blood is green.", "answer": "True"},
    {"question": "The loudest animal is the African Elephant.", "answer": "False"},
    {"question": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"question": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"question": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"question": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"question": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"question": "Google was originally called 'Backrub'.", "answer": "True"},
    {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"question": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"question": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"question": "The Great Wall of China is visible from the Moon.", "answer": "False"},
    {"question": "Lightning never strikes the same place twice.", "answer": "False"},
    {"question": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"question": "An octopus has three hearts.", "answer": "True"},
    {"question": "Bananas grow on trees.", "answer": "False"},
    {"question": "Vikings wore horned helmets in battle.", "answer": "False"},
    {"question": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"question": "There are more fake flamingos in the world than real ones.", "answer": "True"},
    {"question": "Humans share about 60 percent of their DNA with bananas.", "answer": "True"},
    {"question": "A crocodile can stick its tongue out.", "answer": "False"},
    {"question": "The Eiffel Tower can grow taller in summer.", "answer": "True"},
    {"question": "Adult humans have 206 bones.", "answer": "True"},
    {"question": "Sharks are mammals.", "answer": "False"},
    {"question": "Sound travels faster in air than in water.", "answer": "False"},
    {"question": "The inventor of the lightbulb was Thomas Edison.", "answer": "True"},
    {"question": "Bats are blind.", "answer": "False"},
    {"question": "Humans can distinguish over a million different colors.", "answer": "True"},
    {"question": "The human body has four lungs.", "answer": "False"},
    {"question": "The moon has its own gravity.", "answer": "True"},
    {"question": "Tomatoes are vegetables.", "answer": "False"},
    {"question": "Antarctica is the largest desert in the world.", "answer": "True"},
    {"question": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"question": "Your fingernails grow faster than your toenails.", "answer": "True"},
    {"question": "Water boils at 90°C.", "answer": "False"},
    {"question": "Chameleons change color to blend in with their surroundings.", "answer": "False"},
    {"question": "Ostriches bury their heads in the sand to hide.", "answer": "False"},
    {"question": "There are five different blood groups.", "answer": "False"},
    {"question": "The longest river in the world is the Amazon River.", "answer": "False"},
    {"question": "The blue whale is the largest animal to have ever lived.", "answer": "True"},
    {"question": "Humans have five senses.", "answer": "False"},
    {"question": "Some turtles can breathe through their butts.", "answer": "True"},
    {"question": "Sloths can hold their breath longer than dolphins.", "answer": "True"},
    {"question": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"question": "The human heart is on the left side of the chest.", "answer": "False"},
    {"question": "Honey never spoils.", "answer": "True"},
    {"question": "All spiders spin webs.", "answer": "False"},
    {"question": "Humans can breathe and swallow at the same time.", "answer": "False"}
]
